### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by alexandrempm** [hmalphettes/kibana-auth-plugin#4]
Hi Guys

I installed this plugin and I didn't find where I can change the passoword.
How I can change the default password and create new users?
I'm using the username admin and password admin.
Can anyone help me?

**Comment by lmangani** [comment]
Hi @alexandrempm 
With the bare plugin alone, you can only set the users:password as ENV variables when running Kibana:

```
LOCAL_AUTH_LOGINS=admin:password,foo:bar bin/kibana
```

**Comment by alexandrempm** [comment]
This settings stay in this file?

E:\www\kibana\installedPlugins\kibana-auth-plugin\docker

Content

FROM mhart/alpine-node
MAINTAINER hmalphettes@gmail.com

ENV KIBANA_VERSION 4.5.0

RUN apk add --update curl && \
  ( curl -Lskj https://download.elastic.co/kibana/kibana/kibana-${KIBANA_VERSION}-linux-x64.tar.gz | \
  gunzip -c - | tar xf - ) && \
  mv /kibana-$KIBANA_VERSION-linux-x64 /kibana && \
  rm -rf /kibana/node && \
  rm /kibana/bin/_.bat && \
  cd /kibana && \
  npm i hapi-auth-cookie && \
  bin/kibana plugin --install kibana-auth-plugin -u https://github.com/hmalphettes/kibana-auth-plugin/archive/master.tar.gz && \
  apk del curl && \
  rm -rfv /var/cache/apk/_ /tmp/\* /var/tmp/\* /root/.npm

ENV LOCAL_AUTH_LOGINS=admin:password
EXPOSE 5601

CMD ["/kibana/bin/kibana"]

**Comment by alexandrempm** [comment]
Hi 

Is there some how to do?
That can explain how I can create new users account and change the default password of user admin.

**Comment by ubinix-warun** [comment]
@alexandrempm
LOCAL_AUTH_LOGINS=admin:password,foo:bar,**newuser:newpass** bin/kibana
I hope this will help.

**Comment by alexandrempm** [comment]
I'm using the kibana on Windows server, what isn't clear for me is where I have to set this information:

LOCAL_AUTH_LOGINS=admin:password,foo:bar,newuser:newpass bin/kibana

and on Windows System how I can set this settings, this line is correct?

LOCAL_AUTH_LOGINS=admin:password,foo:bar,test:test E:\www\kibana\bin\kibana

If in a configuration file, or create some environment variable of the system.

If you can help me with this question I'll stay thankful.

Thanks

**Comment by lmangani** [comment]
I don't have a windows box to test this with but try use the following format:

```
C:\Users\opt\kibana>set LOCAL_AUTH_LOGINS=admin:password,foo:bar,newuser:newpass
```

**Comment by alexandrempm** [comment]
I created the environment variable of system on windows:

LOCAL_AUTH_LOGINS=admin:password,foo:bar123,guest:guestnewpass E:\www\kibana\bin
\kibana

The first user "admin" and second user "foo" is working very well, but the last user "guest" isn't working.

I had to restart server to work.

**Comment by lmangani** [comment]
You might have to terminate the string for proper parsing - if you still need help feel free to reopen
